export const kingLijstArray = [
  {
    titel: '22-11-1967',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://stephenkingcoverUrls.com/wp-content/uploads/2021/04/1122-2011-Netherlands-Luitingh-Sijthoff2-min.jpg',
    taal: 'Nederlands',
    originele_titel: '22-11-1963',
    jaar_van_uitgave: '2011',
  },
  {
    titel: '4 SEIZOENEN',
    auteur: 'Stephen King',
    serie: '(DE ONTSNAPPING/DE LEERLING/HET LIJK/DE ADEMHALINGSMETHODE)',
    coverUrl:
      'https://stephenkingcoverUrls.com/wp-content/uploads/2021/02/DS-1989-Netherlands-Luitingh-Sijthoff-min.jpg',
    taal: 'Nederlands',
    originele_titel: 'Different Seasons',
    jaar_van_uitgave: '1982',
  },
  {
    titel: '4 X STEPHEN KING',
    auteur: 'Stephen King',
    serie: '(RAZERNIJ/DE MARATHON/WERK IN UITVOERING/VLUCHT NAAR DE TOP)',
    coverUrl: 'https://media.s-bol.com/OEmg38pRGQYL/Y6N5PRY/537x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Bachman Books ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'AARDEDONKER ZONDER STERREN',
    auteur: 'Stephen King',
    serie: '(1922/GROTE TRUCKER/DE VERLENGING/EEN GOED HUWELIJK)',
    coverUrl: 'https://media.s-bol.com/qoZOEZ0LL4kp/1nn980/778x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Full Dark, No Stars ',
    jaar_van_uitgave: '2010',
  },
  {
    titel: 'ACHTBAAN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://boekenfan.nl/wp-content/uploads/2021/11/Achtbaan-Stephen-King.jpg',
    taal: 'Nederlands',
    originele_titel: 'Riding the Bullet ',
    jaar_van_uitgave: '2001',
  },
  {
    titel: 'ALLES IS EVENTUEEL',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/grV7N3yAWZY/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Everything is Eventual ',
    jaar_van_uitgave: '2002',
  },
  {
    titel: 'ALS HET BLOEDT',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/jm2N64JwPP75/rkrkgB6/781x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'If it bleeds ',
    jaar_van_uitgave: '2020',
  },
  {
    titel: 'BEZETEN STAD',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/964/1516/cms_visual_1486220.jpg_1601989743000_964x1516_0.8_p-5b37625743.webp',
    taal: 'Nederlands',
    originele_titel: "Salem's Lot ",
    jaar_van_uitgave: '1982',
  },
  {
    titel: 'BILLY SUMMERS',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/NmxypwVPZ0l8/W6Ek2zJ/547x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'Billy Summers ',
    jaar_van_uitgave: '2021',
  },
  {
    titel: 'CARRIE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://boekenfan.nl/wp-content/uploads/2021/11/Carrie-Stephen-King.jpg',
    taal: 'Nederlands',
    originele_titel: 'Carrie ',
    jaar_van_uitgave: '1975',
  },
  {
    titel: 'CHRISTINE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/xEGw98XXNn3q/1woxP8j/772x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Christine ',
    jaar_van_uitgave: '1983',
  },
  {
    titel: 'CUJO',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/On7zJ5q1121E/gJqBOPY/679x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Cujo ',
    jaar_van_uitgave: '1982',
  },
  {
    titel: 'DE BALLADE VAN DE FLEXIBELE KOGEL',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://s.boekenplatform.nl/bk/15/5d/73/de-ballade-van-de-flexibele-kogel.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Ballad of the Flexible Bullet',
    jaar_van_uitgave: '1984',
  },
  {
    titel: 'DE BEPROEVING',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/JKwznMQJ91PK/gJq1Mw9/546x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Stand ',
    jaar_van_uitgave: '1984',
  },
  {
    titel: 'DE BUITENSTAANDER',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/Z6OqoNKVnlpg/550x839.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Outsider',
    jaar_van_uitgave: '2018',
  },
  {
    titel: 'DE COLORADO KID',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/WEmvAXjxyzqJ/rk5nVBw/773x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Colorado Kid ',
    jaar_van_uitgave: '2005',
  },
  {
    titel: 'DE DONKERE TOREN',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://www.readshop.nl/images/active/carrousel/fullsize/9789021026381_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 7: The Dark Tower ',
    jaar_van_uitgave: '2005',
  },
  {
    titel: 'DE DUISTERE KANT',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://assets.lastdodo.com/image/ld_large/plain/assets/catalog/assets/2014/3/5/6/b/2/pdf_6b2cb94e-a4a4-11e3-92e2-829b43c01455.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Half ',
    jaar_van_uitgave: '1989',
  },
  {
    titel: 'DE EERLIJKE VINDER',
    auteur: 'Stephen King',
    serie: 'MR. MERCEDES',
    coverUrl: 'https://media.s-bol.com/xkkonZBLLn19/782x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Finders Keepers ',
    jaar_van_uitgave: '2015',
  },
  {
    titel: 'DE GLOED',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://assets.lastdodo.com/image/ld_large/plain/assets/catalog/assets/2024/1/30/e/4/f/pdf_e4f879c6-bf5a-11ee-9451-8166e49c76cc.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Tommyknockers ',
    jaar_van_uitgave: '1988',
  },
  {
    titel: 'DE LEERLING',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/gn7VRBXEBGlD/515x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'Apt Pupil',
    jaar_van_uitgave: '1982',
  },
  {
    titel: 'DE MARATHON',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/WQ3y1Y2VxNJW/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Long Walk ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'DE NOODZAAK',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/1181/1800/cms_visual_1527631.jpg_1608130273000_1181x1800_0.8_p-b01caee2cd.webp',
    taal: 'Nederlands',
    originele_titel: 'Needful Things',
    jaar_van_uitgave: '1992',
  },
  {
    titel: 'DE OGEN VAN DE DRAAK',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://www.sassafrass-store.com/files/images/23435.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Eyes of the Dragon ',
    jaar_van_uitgave: '1987',
  },
  {
    titel: 'DE ONTVOERING',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://api.bruna.nl/images/active/carrousel/fullsize/9789021037370_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'Blaze ',
    jaar_van_uitgave: '2007',
  },
  {
    titel: 'DE REGELAARS',
    auteur: 'Richard Bachman',
    serie: '',
    coverUrl: 'https://media.s-bol.com/EXBmBq1n4ovg/RjgjEq/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Regulators ',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'DE SCHERPSCHUTTER',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://media.s-bol.com/3nlPOqgMJp9A/wpNMJxg/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 1: The Gunslinger ',
    jaar_van_uitgave: '1988',
  },
  {
    titel: 'DE SCHNABBEL (en andere verhalen)',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://files.booksinbelgium.be/image-large/91169e40-86d6-4256-b51a-203dfa4bc6b8.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Wedding Gig',
    jaar_van_uitgave: '1980',
  },
  {
    titel: 'DE SHINING',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/mLqr8nkZWxE/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Shining ',
    jaar_van_uitgave: '1983',
  },
  {
    titel: 'DE SPELBREKER',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://www.boekenwebsite.nl/files/imagecache/vergroting/de-spelbreker_1.jpg',
    taal: 'Nederlands',
    originele_titel: "Gerald's Game ",
    jaar_van_uitgave: '1992',
  },
  {
    titel: 'DE STORM VAN DE EEUW',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://api.bruna.nl/images/active/carrousel/fullsize/9789024578078_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'Storm Of The Century ',
    jaar_van_uitgave: '1999',
  },
  {
    titel: 'DE TALISMAN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://m.media-amazon.com/images/I/917jFhgDv3L._UF1000,1000_QL80_.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Talisman ',
    jaar_van_uitgave: '1985',
  },
  {
    titel: 'DE VERVLOEKING',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/q2kPrWnVMV80/ZwqZog/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Thinner ',
    jaar_van_uitgave: '1985',
  },
  {
    titel: 'DE WIND DOOR HET SLEUTELGAT',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://media.s-bol.com/8zlrNm9wxPXr/VnmVlz/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Wind Through The Keyhole ',
    jaar_van_uitgave: '2012',
  },
  {
    titel: 'DESPERATION',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/vxkrkQoK1p2r/kX5XqE/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'Desperation ',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'DODELIJK DILEMMA',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/mLrv9WNg0zE/829x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dead Zone ',
    jaar_van_uitgave: '1980',
  },
  {
    titel: 'DODENWAKE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/380/600/cms_visual_1407163.jpg_1593095183000_380x600_0.8_p-3c20453642.webp',
    taal: 'Nederlands',
    originele_titel: 'Pet Sematary ',
    jaar_van_uitgave: '1984',
  },
  {
    titel: "DOLAN'S CADILLAC",
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/xlmpX4PAqPRJ/540x840.jpg',
    taal: 'Nederlands',
    originele_titel: "Dolan's Cadillac ",
    jaar_van_uitgave: '1992',
  },
  {
    titel: 'DOLORIS CLAIBORNE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://m.media-amazon.com/images/I/81p9dNU6wUL._UF894,1000_QL80_.jpg',
    taal: 'Nederlands',
    originele_titel: 'Dolores Claiborne ',
    jaar_van_uitgave: '1993',
  },
  {
    titel: 'DR. SLEEP',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://m.media-amazon.com/images/I/71At7VPGc6L.jpg',
    taal: 'Nederlands',
    originele_titel: 'Doctor Sleep ',
    jaar_van_uitgave: '2013',
  },
  {
    titel: 'DROMENVANGER',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/yAOLlNzKog6R/9Oo7XP/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Dreamcatcher ',
    jaar_van_uitgave: '2001',
  },
  {
    titel: 'DROOMLANDSCHAPPEN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/1130/1800/cms_visual_1488312.jpg_1602260449000_1130x1800_0.8_p-eab910845c.webp',
    taal: 'Nederlands',
    originele_titel: 'Dreamscapes',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'DUISTERE KRACHTEN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/ZB4NpBN0PBv8/lYyjJxr/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Skeleton Crew ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'DUISTERE ZAKEN',
    auteur: 'Stephen King',
    serie:
      '(Twee getalenteerde rotzakken / Danny Coughlins nare droom / Ratelslangen / De Dromers / De Antwoordman)',
    coverUrl: 'https://media.s-bol.com/YA6NrvRjg3Yn/ADzq9nO/760x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'You like it Darker ',
    jaar_van_uitgave: '2023',
  },
  {
    titel: 'DUMA',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/7r62OK1qMovr/9rzRJDP/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Duma Key ',
    jaar_van_uitgave: '2008',
  },
  {
    titel: 'EEN LIED VAN SUSANNAH',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://www.readshop.nl/images/active/carrousel/fullsize/9789021026190_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 6: A Song of Susannah ',
    jaar_van_uitgave: '2004',
  },
  {
    titel: 'EENMALIGE ZONDE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/mZZr4n007EjG/765x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Morality',
    jaar_van_uitgave: '2011',
  },
  {
    titel: 'FAIRY TALE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://images.mind-books.nl/libris/book/coverUrl/9789049207588?hash=a1f0d28&width=415',
    taal: 'Nederlands',
    originele_titel: 'Fairy Tale',
    jaar_van_uitgave: '2022',
  },
  {
    titel: 'GEVANGEN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAEsa-qjGitHKWPhIKN3JdhytCxKrGfr7l9ohwgTcORj4XgkpV3GfynYuRJFfmc2QkdaM&usqp=CAU',
    taal: 'Nederlands',
    originele_titel: 'Under The Dome ',
    jaar_van_uitgave: '2009',
  },
  {
    titel: "GWENDY'S KNOPPENKIST",
    auteur: 'Stephen King',
    serie: 'DE GWENDY TRILOGIE',
    coverUrl:
      'https://www.stumpel.nl/media/mf_webp/jpg/media/catalog/product/cache/2c143004342cf6e587a2eb62a7d75e14/9/7/9789049204815_fv_01.webp',
    taal: 'Nederlands',
    originele_titel: "Gwendy's Buttonbox trilogy ",
    jaar_van_uitgave: '2024',
  },
  {
    titel: "GWENDY'S LAATSTE TAAK",
    auteur: 'Stephen King',
    serie: 'DE GWENDY TRILOGIE',
    coverUrl:
      'https://www.stumpel.nl/media/mf_webp/jpg/media/catalog/product/cache/2c143004342cf6e587a2eb62a7d75e14/9/7/9789049204815_fv_01.webp',
    taal: 'Nederlands',
    originele_titel: "Gwendy's Buttonbox trilogy ",
    jaar_van_uitgave: '2024',
  },
  {
    titel: "GWENDY'S MAGISCHE VEER",
    auteur: 'Stephen King',
    serie: 'DE GWENDY TRILOGIE',
    coverUrl:
      'https://www.stumpel.nl/media/mf_webp/jpg/media/catalog/product/cache/2c143004342cf6e587a2eb62a7d75e14/9/7/9789049204815_fv_01.webp',
    taal: 'Nederlands',
    originele_titel: "Gwendy's Buttonbox trilogy ",
    jaar_van_uitgave: '2024',
  },
  {
    titel: 'HARTEN IN ATLANTIS',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/3V21zKqlPVGQ/lRpp0E6/781x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Hearts in Atlantis ',
    jaar_van_uitgave: '1999',
  },
  {
    titel: 'HET',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://www.stichtingboekenwerk.nl/shop/wp-content/uploads/2022/02/IMG_5379.jpg',
    taal: 'Nederlands',
    originele_titel: 'It ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'HET GEHEIM VAN DE BUICK',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://www.readshop.nl/images/active/carrousel/fullsize/9789021037363_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'From A Buick 8 ',
    jaar_van_uitgave: '2002',
  },
  {
    titel: 'HET INSTITUUT',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/vBXJYEOxGlK0/WnP2pYQ/546x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Institute ',
    jaar_van_uitgave: '2019',
  },
  {
    titel: 'HET MEISJE DAT HIELD VAN TOM GORDON',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/383/600/cms_visual_1028206.jpg_1520431296000_383x600_0.8_p-6df878adb4.webp',
    taal: 'Nederlands',
    originele_titel: 'The Girl Who Loved Tom Gordon ',
    jaar_van_uitgave: '1999',
  },
  {
    titel: 'HET RAK (en andere verhalen)',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/4rkYmmrN9n6J/rk5BgwK/745x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Reach',
    jaar_van_uitgave: '1981',
  },
  {
    titel: 'HET TEKEN VAN DRIE',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://www.readshop.nl/images/active/carrousel/fullsize/9789021037639_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 2: The Drawing of the Three ',
    jaar_van_uitgave: '1989',
  },
  {
    titel: 'HET VERLOREN RIJK',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://www.readshop.nl/images/active/carrousel/fullsize/9789021037394_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 3: The Waste Lands ',
    jaar_van_uitgave: '1992',
  },
  {
    titel: 'HOLLY',
    auteur: 'Stephen King',
    serie: 'HOLLY GIBNEY',
    coverUrl: 'https://media.s-bol.com/jm2NL37RLZPz/1woxxxG/830x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Holly',
    jaar_van_uitgave: '2023',
  },
  {
    titel: 'HOOGSTE VERSNELLING',
    auteur: 'Stephen King & Joe Hill',
    serie: '',
    coverUrl: 'https://media.s-bol.com/jxp3jZpPxgR/822x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Throttle ',
    jaar_van_uitgave: '2013',
  },
  {
    titel: 'INSOMNIA',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK02oqe4MH2uv4p4ScfTbGSuQRIJxpWXEESQ&s',
    taal: 'Nederlands',
    originele_titel: 'Insomnia ',
    jaar_van_uitgave: '1994',
  },
  {
    titel: 'JOYLAND',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/BP5mrAvrn21n/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'Joyland ',
    jaar_van_uitgave: '2013',
  },
  {
    titel: 'KAT UIT DE HEL',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://whatsnewtoday.nl/wp-content/uploads/2022/06/Kat-uit-de-hel-Stephen-King-en-anderen-9789057950322-scaled.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Cat From Hell',
    jaar_van_uitgave: '1977',
  },
  {
    titel: 'LATER',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/WynXjQ9mpYYX/5yvq2n8/797x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Later ',
    jaar_van_uitgave: '2021',
  },
  {
    titel: "LISEY'S VERHAAL",
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/509/800/cms_visual_9915.jpg_1403605148000_509x800_0.8_p-f72d489759.webp',
    taal: 'Nederlands',
    originele_titel: "Lisey's Story ",
    jaar_van_uitgave: '2006',
  },
  {
    titel: 'MACABER CARNAVAL',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/RymZqDVGgkWR/n5o2lMY/712x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Danse Macabre ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'MACABERE LIEFDE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/1171/1800/cms_visual_1444598.jpg_1595688314000_1171x1800_0.8_p-1ec281100d.webp',
    taal: 'Nederlands',
    originele_titel: 'Night Shift',
    jaar_van_uitgave: '1978',
  },
  {
    titel: 'MISERY',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Misery_%281987%29_front_coverUrl%2C_first_edition.jpg/1200px-Misery_%281987%29_front_coverUrl%2C_first_edition.jpg',
    taal: 'Nederlands',
    originele_titel: 'Misery ',
    jaar_van_uitgave: '1987',
  },
  {
    titel: 'MOBIEL ',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/NmxyprwkJ7Dv/gJq1wql/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'Cell ',
    jaar_van_uitgave: '2006',
  },
  {
    titel: 'MR. MERCEDES',
    auteur: 'Stephen King',
    serie: 'MR. MERCEDES',
    coverUrl: 'https://m.media-amazon.com/images/I/91ejxgOhBJL._UF1000,1000_QL80_.jpg',
    taal: 'Nederlands',
    originele_titel: 'Mr. Mercedes ',
    jaar_van_uitgave: '2014',
  },
  {
    titel: 'NACHTMERRIES',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/1116/1800/cms_visual_1488314.jpg_1602260488000_1116x1800_0.8_p-8541816cb0.webp',
    taal: 'Nederlands',
    originele_titel: 'Nightmares',
    jaar_van_uitgave: '1993',
  },
  {
    titel: 'NACHTMERRIES EN DROOMLANDSCHAPPEN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/images/cached/resample/webp/data/uploads/388/600/cms_visual_1026373.jpg_1690363508000_388x600_0.8_p-f2cb2959f3.webp',
    taal: 'Nederlands',
    originele_titel: 'Nightmares & Dreamscapes ',
    jaar_van_uitgave: '1993',
  },
  {
    titel: 'OGEN VAN VUUR',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://www.boekenwebsite.nl/files/imagecache/vergroting/ogen-van-vuur.jpg',
    taal: 'Nederlands',
    originele_titel: 'Firestarter ',
    jaar_van_uitgave: '1981',
  },
  {
    titel: 'REVIVAL',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://api.bruna.nl/images/active/carrousel/fullsize/9789021025285_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'Revival ',
    jaar_van_uitgave: '2014',
  },
  {
    titel: 'ROSE MADDER',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1660826989i/10619.jpg',
    taal: 'Nederlands',
    originele_titel: 'Rose Madder',
    jaar_van_uitgave: '1995',
  },
  {
    titel: 'ROSIE',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/6q6421Gr25LV/wpNMXkR/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Rose Madder ',
    jaar_van_uitgave: '1995',
  },
  {
    titel: 'SATANSKINDEREN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/jv6Jl8EPzjBz/o2Bpzyz/770x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Nightshift ',
    jaar_van_uitgave: '1976',
  },
  {
    titel: 'SCHEMERWERELD',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://www.readshop.nl/images/active/carrousel/fullsize/9789024578153_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'Four Past Midnight ',
    jaar_van_uitgave: '1991',
  },
  {
    titel: 'SCHONE SLAAPSTERS',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/qJqzN2vGvwD/550x833.jpg',
    taal: 'Nederlands',
    originele_titel: 'Sleeping Beauties ',
    jaar_van_uitgave: '2017',
  },
  {
    titel: 'SILVER BULLET',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://static.boekenbalie.nl/media/58/de/19/1620372590/boekenbalie_9789024510610_coverUrl.jpg?ts=1731883849',
    taal: 'Nederlands',
    originele_titel: 'Cycle of the Werewolf ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'SKELETON CREW',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://api.bruna.nl/images/active/carrousel/fullsize/9781668207741_front.jpg',
    taal: 'Engels',
    originele_titel: 'Skeleton Crew',
    jaar_van_uitgave: '1975',
  },
  {
    titel: 'THE MIST (Dichte Mist)',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://media.s-bol.com/MKnwol4O7x0P/QgBolG/771x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Mist',
    jaar_van_uitgave: '1980',
  },
  {
    titel: 'THE REGULATORS',
    auteur: 'Richard Bachman',
    serie: '',
    coverUrl: 'https://m.media-amazon.com/images/I/71jhK0QdSGL._UF1000,1000_QL80_.jpg',
    taal: 'Engels',
    originele_titel: 'The Regulators ',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'THE WIND THROUGH THE KEYHOLE',
    auteur: 'Stephen King',
    serie: 'THE DARK TOWER',
    coverUrl: 'https://m.media-amazon.com/images/I/81sbfKKDmHL._UF1000,1000_QL80_.jpg',
    taal: 'Engels',
    originele_titel: 'Wind Through The Keyhole, The',
    jaar_van_uitgave: '2012',
  },
  {
    titel: 'TOVERNAARSGLAS',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://api.bruna.nl/images/active/carrousel/fullsize/9789021025353_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 4: Wizard and Glass ',
    jaar_van_uitgave: '1997',
  },
  {
    titel: 'TWEEDUISTER',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://www.deslegte.com/?module=CMS&action=GenerateThumbnail&url=https://www.deslegte.com/tweeduister-de-engelieren-het-geheime-raam-109752/',
    taal: 'Nederlands',
    originele_titel: 'Four Past Midnight ',
    jaar_van_uitgave: '1990',
  },
  {
    titel: 'VEL OVER BEEN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://api.bruna.nl/images/active/carrousel/fullsize/9789021049168_front.jpg',
    taal: 'Nederlands',
    originele_titel: 'Bag of Bones ',
    jaar_van_uitgave: '1998',
  },
  {
    titel: 'VLUCHT NAAR DE TOP',
    auteur: 'Stephen King',
    serie: '(Richard Bachman)',
    coverUrl: 'https://media.s-bol.com/yG8x7rxD5oPn/n50Q884/827x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Running Man ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'WERK IN UITVOERING / VLUCHT NAAR DE TOP',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1378225548i/18454671.jpg',
    taal: 'Nederlands',
    originele_titel: 'Roadwork ',
    jaar_van_uitgave: '1986',
  },
  {
    titel: 'WISSELING VAN DE WACHT',
    auteur: 'Stephen King',
    serie: 'MR. MERCEDES',
    coverUrl: 'https://media.s-bol.com/VNvOWoXRPrwB/690x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'End of Watch ',
    jaar_van_uitgave: '2016',
  },
  {
    titel: 'WOLVEN VAN DE CALLA',
    auteur: 'Stephen King',
    serie: 'DONKERE TOREN',
    coverUrl: 'https://media.s-bol.com/3nlPO8EoOMQp/qxEwO22/539x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Dark Tower 5: Wolves of the Calla ',
    jaar_van_uitgave: '2003',
  },
  {
    titel: 'COFFEY OP DE MIJL',
    auteur: 'Stephen King',
    serie: 'DE GROENE MIJL',
    coverUrl: 'https://media.s-bol.com/gkBPDGNBw8Nr/770x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Coffey on the Mile',
    jaar_van_uitgave: '1996',
  },
  {
    titel: "COFFEY'S HANDEN",
    auteur: 'Stephen King',
    serie: 'DE GROENE MIJL',
    coverUrl: 'https://www.boekenwebsite.nl/files/imagecache/vergroting/coffey039s-handen.jpg',
    taal: 'Nederlands',
    originele_titel: "Coffey's Hands",
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'DE MUIS',
    auteur: 'Stephen King',
    serie: 'DE GROENE MIJL',
    coverUrl: 'https://media.s-bol.com/mLvAZkJD9mp/526x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Mouse on the Mile',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'NACHTREIS',
    auteur: 'Stephen King',
    serie: 'DE GROENE MIJL',
    coverUrl: 'https://media.s-bol.com/qJXQ4JMlqxy/738x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'Night Journey',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'DE TWEE DODE MEISJES',
    auteur: 'Stephen King',
    serie: 'DE GROENE MIJL',
    coverUrl: 'https://media.s-bol.com/NN6XLWBxOEz/741x1200.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Two Dead Girls',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'DE VRESELIJKE DOOD CAN EDUARD DELACROIX',
    auteur: 'Stephen King',
    serie: 'DE GROENE MIJL',
    coverUrl: 'https://media.s-bol.com/RX1pAmRXDrZq/YnBQQ2/533x840.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Bad Death of Eduard Delacroix',
    jaar_van_uitgave: '1996',
  },
  {
    titel: 'IK GRIEZEL VAN GENOT',
    auteur: 'Stephen King en anderen',
    serie: '',
    coverUrl: 'https://kinglijst.netlify.app/src/img/ik_griezel_van_genot.jpg',
    taal: 'Nederlands',
    originele_titel: 'I Shudder At Your Touch',
    jaar_van_uitgave: '1991',
  },
  {
    titel: 'NA ZONSONDERGANG',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://kinglijst.netlify.app/src/img/na_zonsondergang.jpg',
    taal: 'Nederlands',
    originele_titel: 'Just After Sunset',
    jaar_van_uitgave: '2008',
  },
  {
    titel: 'DE BAZAAR VAN BOZE DROMEN',
    auteur: 'Stephen King',
    serie: '',
    coverUrl: 'https://kinglijst.netlify.app/src/img/de_bazeer_van_boze_dromen.jpg',
    taal: 'Nederlands',
    originele_titel: 'The Bazaar Of Bad Dreams',
    jaar_van_uitgave: '2015',
  },
  {
    titel: 'VREES NIET',
    auteur: 'Stephen King',
    serie: 'HOLLY GIBNEY',
    coverUrl: 'https://kinglijst.netlify.app/src/img/vrees_niet.jpg',
    taal: 'Nederlands',
    originele_titel: 'Never Flinch',
    jaar_van_uitgave: '2025',
  },
  {
    titel: 'ZWART HUIS',
    auteur: 'Stephen King & Peter Straub',
    serie: '',
    coverUrl: 'https://kinglijst.netlify.app/src/img/zwart_huis.jpg',
    taal: 'Nederlands',
    originele_titel: 'Black House',
    jaar_van_uitgave: '2001',
  },
  {
    titel: 'Middenmoot',
    auteur: 'Stephen King',
    serie: '',
    coverUrl:
      'https://stephenkingcoverUrls.com/wp-content/uploads/2021/04/1122-2011-Netherlands-Luitingh-Sijthoff2-min.jpg',
    taal: 'Nederlands',
    originele_titel: '22-11-1963',
    jaar_van_uitgave: '2011',
  },
]
